-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_membership_history`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_membership_history
-- *
-- * Stores Membership history parameters for display
-- *
-- *******************************************************/
CREATE TABLE `civicrm_membership_history` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique MembershipHistory ID',
     `contact_id` int unsigned    COMMENT 'FK to Contact',
     `Membership type id` varchar(255)    COMMENT 'Membership Type Id',
     `start_date` tinyint    COMMENT 'Show start Date',
     `end_date` tinyint    COMMENT 'Show End Date'
,
        PRIMARY KEY (`id`)


,          CONSTRAINT FK_civicrm_membership_history_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)    ;
